name: 自动构建

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: 0 */24 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    name: 自动构建

    steps:
    - name: 检查是否需要更新
      id: check_update
      run: |
        latest_version="$((curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${vars.CADDY_REPO}/releases/latest) \
          | jq -r '.tag_name')"
        my_version="$(curl -L https://raw.githubusercontent.com/${vars.MY_REPO}/main/lastversion.txt)"

        if [ $latest_version == $my_version ]
        then
          update='false'
        else
          update='true'
        fi

        echo "update=${update}" >> $GITHUB_OUTPUT
        echo "version=${latest_version}" >> $GITHUB_OUTPUT
        echo "是否更新: $update | 最新版本: $latest_version"

    - name: 触发构建
      if: steps.check_update.outputs.update == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: 自动构建 ${{ steps.check_update.outputs.version }}
        client-payload: '{"version": "${{ steps.check_update.outputs.version }}"}'
        
    - name: 删除旧的 workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4